import { A3_PORTRAIT, createPosterSceneSize } from "../constants/paper";
import type { PosterScene } from "../types/scene";

const size = createPosterSceneSize(A3_PORTRAIT, 300);

export const sampleScene: PosterScene = {
  ...size,
  background: {
    fill: "#f7f0e8",
  },
  nodes: [
    {
      id: "bg-panel",
      type: "rect",
      x: 176,
      y: 176,
      width: size.width - 352,
      height: size.height - 352,
      fill: "#13151d",
      radius: 56,
    },
    {
      id: "accent-strip",
      type: "rect",
      x: 176,
      y: 176,
      width: 128,
      height: size.height - 352,
      fill: "#ff8c42",
      radius: 56,
    },
    {
      id: "title",
      type: "text",
      x: 420,
      y: 440,
      width: 2200,
      height: 320,
      text: "Graphic\nDesign NG",
      color: "#fff6eb",
      fontFamily: "\"IBM Plex Sans\", \"Noto Sans SC\", sans-serif",
      fontSize: 210,
      fontWeight: 700,
      lineHeight: 190,
    },
    {
      id: "subtitle",
      type: "text",
      x: 432,
      y: 900,
      width: 1800,
      height: 300,
      text: "A3 / 300 DPI / JPG output\n2D composition with embedded 3D objects",
      color: "#d6dfef",
      fontFamily: "\"IBM Plex Sans\", \"Noto Sans SC\", sans-serif",
      fontSize: 72,
      fontWeight: 400,
      lineHeight: 98,
    },
    {
      id: "orbital-knot",
      type: "mesh3d",
      x: 1980,
      y: 1520,
      width: 1180,
      height: 1180,
      mesh: "torusKnot",
      color: "#f2c078",
      background: "#13151d",
      rotationX: 0.9,
      rotationY: 0.4,
      rotationZ: 0.2,
    },
    {
      id: "footer",
      type: "text",
      x: 430,
      y: 4300,
      width: 1800,
      height: 120,
      text: "Render pipeline: React shell + Canvas compositor + Three.js subscene renderer",
      color: "#ffbf8a",
      fontFamily: "\"IBM Plex Sans\", \"Noto Sans SC\", sans-serif",
      fontSize: 54,
      fontWeight: 500,
      lineHeight: 60,
    },
  ],
};
